version: 2

before:
  hooks:
    - go mod tidy
builds:
  - main: ./
    id: uds-security-hub
    binary: uds-security-hub
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - uds-security-hub
checksum:
  name_template: "{{ .ProjectName }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: true
sboms:
  - artifacts: binary
    documents:
      - "{{ .Binary }}_{{ .Os }}_{{ .Arch }}.spdx.sbom.json"
